//
//  KPVehiclesListRouter.swift
//  koolicarproject
//
//  Created by Stephan Yannick on 30/09/2016.
//  Copyright (c) 2016 koolicar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

public protocol KPVehiclesListRouterInput {
}

final class KPVehiclesListRouter: KPGenericRouter<KPVehiclesListViewController>, KPVehiclesListRouterInput {
    
    // MARK: Navigation
    
    // MARK: Communication

}
