//
//  KPVehiclesListRouter.swift
//  koolicarproject
//
//  Created by Stephan Yannick on 30/09/2016.
//  Copyright (c) 2016 koolicar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol KPVehiclesListRouterInput {
}

final class KPVehiclesListRouter: KPVehiclesListRouterInput {
    
    weak var viewController: KPVehiclesListViewController!
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
        /* if segue.identifier == "ShowSomewhereScene" { } */
    }
}
