//
//  KPVehiclesListInteractor.swift
//  koolicarproject
//
//  Created by Stephan Yannick on 30/09/2016.
//  Copyright (c) 2016 koolicar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit


public protocol KPVehiclesListInteractorInput {
    func fetchVehicleData()
    var vehicles: [Vehicle] { get }
}

public protocol KPVehiclesListInteractorOutput {
    func presentVehicles()
    func presentFailVehicles(error: KPVehiclesListError)
}

final class KPVehiclesListInteractor: KPGenericInteractor, KPVehiclesListInteractorInput {
    
    var output: KPVehiclesListInteractorOutput!
    var worker: KPVehiclesListWorker!
    
    private(set) var vehicles: [Vehicle] = []
    
    // MARK: Business logic
    //TODO: intépreter les retours fails
    func fetchVehicleData() {
        guard KPHelpers.isConnectedToNetwork() else {
            output.presentFailVehicles(error: .noNetwork)
            return
        }
        KPVehiclesListWorker.requestVehicles() {
            result in
            switch (result) {
            case let .success(result):
                self.vehicles = result
                self.output.presentVehicles()
                break
            
            case .failure(_):
                self.output.presentFailVehicles(error: .noData)
                break
            }
        }
    }
}
