//
//  KPVehiclesListViewController.swift
//  koolicarproject
//
//  Created by Stephan Yannick on 30/09/2016.
//  Copyright (c) 2016 koolicar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol KPVehiclesListViewControllerInput {
}

protocol KPVehiclesListViewControllerOutput {
}

final class KPVehiclesListViewController: UIViewController, KPVehiclesListViewControllerInput {
    
    var output: KPVehiclesListViewControllerOutput!
    var router: KPVehiclesListRouter!
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        KPVehiclesListConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    // MARK: Event handling
    
    // MARK: Display logic
    
}
