//
//  KPVehiclesListModels.swift
//  koolicarproject
//
//  Created by Stephan Yannick on 30/09/2016.
//  Copyright (c) 2016 koolicar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

/**
 * KPVehiclesListError
 * Gestion des erreur sur le controller KPVehiclesList avec description pour l'affichage en popup
 */
public enum KPVehiclesListError: String, Error {
    case noNetwork  =  "Vous n'avez pas internet"
    case noData     =  "Aucun donnée est disponible"
}

struct KPVehiclesListModel {
    
    struct KPVehiclesListRequest { }
    
    struct KPVehiclesListResponse { }
    
    struct KPVehiclesListViewModel { }
    
}

