//
//  KPGenericViewController.swift
//  koolicarproject
//
//  Created by Stephan Yannick on 29/09/2016.
//  Copyright (c) 2016 koolicar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

public class KPGenericViewController: UIViewController {
    
    // MARK: Object lifecycle
    
    override public func awakeFromNib() {
        super.awakeFromNib()
    }
    
    // MARK: View lifecycle
    
    override public func viewDidLoad() {
        super.viewDidLoad()
    }
    
    // MARK: Internal method
    
    internal func closeKeyboard() {
        self.resignFirstResponder()
        self.view.endEditing(true)
    }
    internal func addGestureCloseKeyboard(view:UIView) {
        view.addTapGesture(tapNumber: 1, target: self, action: #selector(KPGenericViewController.closeKeyboard))
    }
    
    internal func getCellError() -> UITableViewCell {
        let cell = UITableViewCell()
        cell.backgroundColor = UIColor.red
        return cell
    }
}
